#!/bin/bash

SRC_DIR="$( cd "$( dirname "$0" )" && pwd )"
CVMFS_DIR=$SRC_DIR/cvmfs
FS_DIR=$SRC_DIR/fs
THIRD_PARTY_DIR=$SRC_DIR/third_party

emcc $* \
    -s WASM=0 \
    --pre-js $THIRD_PARTY_DIR/jsrsasign-all-min.js \
    --pre-js $THIRD_PARTY_DIR/sha3.js \
    --pre-js $THIRD_PARTY_DIR/pako_inflate.min.js \
    --pre-js $THIRD_PARTY_DIR/sql.js \
    --pre-js $CVMFS_DIR/cvmfs.js \
    --pre-js $CVMFS_DIR/fetcher.js \
    --pre-js $CVMFS_DIR/master_keys.js \
    --pre-js $CVMFS_DIR/repo.js \
    --pre-js $CVMFS_DIR/util.js \
    --js-library $FS_DIR/library_cvmfs.js \
    --js-library $FS_DIR/library_fs.js